spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.123.122:3306/studb
      username: root
      password: abc123
      # ?????????????
      initial-size: 8
      # ??????????
      min-idle: 5
      # ?????????
      max-active: 20
      # ????????????????
#      max-wait: 60000
#      # ??????????????????timeBetweenEvictionRunsMillis???validationQuery?????????
#      test-while-idle: true
#      # ?????????????testWhileIdel?????
#      time-between-eviction-runs-millis: 60000
#      # ????????????????????????????????????(??????????????)
#      min-evictable-idle-time-millis: 30000
      # ??????????????sql ?????????(oracle?? select 1 from dual)
      validation-query: select 1
      # ????????validationQuery????????,???????,???true
      test-on-borrow: false
      # ????????validationQuery????????,???????,???true
      test-on-return: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true

#      # ????preparedStatement, ???PSCache,PSCache???????????????????oracle,?mysql??????
#      pool-prepared-statements: false
#      # ???PSCache???????0????0??poolPreparedStatements???????true??Druid??????Oracle?PSCache??????????????????????????100
#      max-pool-prepared-statement-per-connection-size: -1
#      # ????DruidDataSource?????
#      use-global-data-source-stat: true
logging:
  level:
    root: info

# mybatis -????mybatis-config.xml
# mapperxml?????  settings???  ?????...
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.wggglggg.springbootbase05mybatis.model.po
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl